### ISSUE TITLE
Move the repo to the `jupyterlite` organization on GitHub 

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#218]
Since the project is progressively getting more traction and contributors, we should start thinking about moving the repo to the `jupyterlite` organization: https://github.com/jupyterlite

This will have the following benefits:

- better looking than under a GitHub user account
- the organization would also have satellite repos such as cookiecutters, extra kernels and GitHub pages template (https://github.com/jtpio/jupyterlite-demo)
- another demo site could be published to https://jupyterlite.github.io

Related questions and points to consider:

- do we want to make JupyterLite a Jupyter sub-project?
- if so, that would mean proposing it to https://github.com/jupyter/enhancement-proposals
- we might want to publish `0.1.0` first and close the [MVP project](https://github.com/jtpio/jupyterlite/projects/1) 
- make sure the name and logos don't cause any issue

### TODO

- [x] Move the repo to https://github.com/jupyterlite
- [x] Update ReadTheDocs configuration
- [x] Update links to point to https://github.com/jupyterlite/jupyterlite
- [x] Cut a new alpha on PyPI

**Comment by bollwyvl** [comment]
Hooray shared repos/projects. After writing all of the below, I don't see any blockers to making the org change basically immediately, and continuing to ship `alphas` from there.

> satellite repos

Not a blocker, but to break up the monorepo for js-level stuff, we'll need

- #104 
- #118

> do we want to make JupyterLite a Jupyter sub-project?

Having it be an official Jupyter subproject is certainly attractive, but I don't think that should hold up too much progress or this move. 

The biggest win, in my mind, is we could then lobby for an efficient, in-browser `https://jupyter.org/try`. However, we couldn't release and then promote a DDoS of  `pypi.org`. This would need, as table stakes, 
- #137 (to cut down on repeat bandwidth needs)
- ideally #45 (and have a self-hosted subset of whls needed to enable any shipped demo content)

Further, we'd probably need to:

- #116 solidify/rename the py kernel up to all of the non-debugger messages
- solidify the js kernel up to same
- have a :fire: theme that _clearly_ distinguishes lite
- support much more of the good builtins: translations, licenses, workspaces (#139)
- maybe integrate with sphinx (#149)... 
  - though jupyter.org runs some other contraption, but probably shouldn't

But again, these are longer-term goals.

> we might want to publish 0.1.0 first and close the MVP project

:shrug: Unless we want to call _being an org_ part of MVP that demonstrates automated release, etc. We may also want to wait on a `0.1.0` for our upstreams to be out of beta... and not be breaking all of our sweet demo toys.

> make sure the name and logos don't cause any issue

I think we've been dotting our `i`'s and crossing our `t`'s well enough for trademark/attribution purposes. [Jo](https://docs.google.com/presentation/d/1sh1LEze9wPrSuwzbCeLy0US8Fe3t2xD9ZNwlLvjSD4A/) is also at the ready to be a supercute mascot.

**Comment by dsblank** [comment]
I wonder about the name `jupyterlite`... are you married to that name? When I first heard it, I got the wrong impression and thought it might be a stripped-down Jupyter. But that is not it at all! Are you open to other ideas?

**Comment by jtpio** [comment]
@dsblank Naming things is always difficult :)

We briefly discussed the name with a couple of people offline and it felt relevant for this project. And then the name kind of stuck.

Also the name sounds a bit similar to TensorFlow Lite which is TensorFlow for edge devices.

**Comment by dsblank** [comment]
Oh, I know naming is hard. We still haven't named our son, and he is 26 years old :)

Seriously, though, this project reminds me of the "Live" versions of Linux distros, like Ubuntu. What about JupyterLive?

**Comment by bollwyvl** [comment]
:wave: @dsblank so nice to see you here!

More creative thinking around branding/design are always welcome: we're just a couple nerds tap-dancing along, but _somebody_ is going to white label this and make money re-selling it with some trivial extensions (e.g. _I receive: all your data in my walled garden, you receive: insert-proprietary-saas-integration-here_)

>  a stripped-down Jupyter

Thanks for the vote of confidence, and maybe i'm too close to it, but it is still pretty darned stripped-down... it will be a long road to where:
- it's reproducible, to the point where it's not reliant on 2-3 CDNs all working today the way they worked  yesterday
- the kernels have feature parity (good completion and inspection, much less debugging)
  - also, after the first load, kernels need to start up and get pixels on the page in under a second 
- the "server" supports more of the real server paths
  - `nbconvert` outputs... I have my eyes on in-browser-generated PDF... and more...
- more of the "top 10" fat (server)extensions work transparently, e.g. `jupyterlab-git`, `jupyterlab-github`, `nbdime`, etc.
  - ...and maybe some less-than-top-10 ones, like `jupyterlab-outsource`

> TensorFlow Lite

_this_ is a whacking good idea: we need an example that:
- trains offline in real python 
- exposes tflite in a lite kernel notebook (either js... or py, because we can) running against something non-silly, like `ipywebrtc`

**Comment by dsblank** [comment]
Hey, @bollwyvl ! Nice to be here... very exciting project!

It may be true that this is a reduced Jupyter, but that is not what one should focus on. It is that is live, in the browser. Which is why I like `JupyterLive` or something similar. 

Perhaps I can help by exploring the TensorFlow API in this project.

**Comment by jtpio** [comment]
> After writing all of the below, I don't see any blockers to making the org change basically immediately, and continuing to ship `alphas` from there.

Right. I think the main concern was about the name, to not give the false impression this is (already) an official Jupyter sub-project. But we can probably proceed with the move anyway and see how things go.

Regarding the name, I feel like `JupyterLite` fits well. And the icons and wordmark are also really nice. The word `Live` in `JupyterLive` can be pronounced in two different ways (with different meaning), which can be confusing to some people. Another name that was considered was `Jupytair` but it sounded too close to Altair and Jupyter.

Although it might not look like this at first glance, JupyterLite is still a somehow stripped-down Jupyter, as many things will not work as expected especially regarding the Python kernel (files not visible, some libraries not supported...)

**Comment by jtpio** [comment]
> Perhaps I can help by exploring the TensorFlow API in this project.

It would be really exciting to put up some ML demo in the examples. TensorFlow might be difficult to get to run in Pyodide, but it could also be another ML library.

**Comment by jtpio** [comment]
The repo has been moved: https://github.com/jupyterlite/jupyterlite

You can update your `remote` with:

```
git remote set-url upstream https://github.com/jupyterlite/jupyterlite.git
```

**Comment by jtpio** [comment]
Closing as fixed with the items listed in https://github.com/jupyterlite/jupyterlite/issues/218#issue-937977381 completed.

- https://pypi.org/project/jupyterlite/0.1.0a4/
- https://github.com/jupyterlite/jupyterlite/releases/tag/v0.1.0a4
