### ISSUE TITLE
Update to JupyterLab 4 and Notebook 7

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#826]
### Problem

There is no more development happening on RetroLab: https://github.com/jupyterlab/retrolab#%EF%B8%8F-retrolab-and-notebook-v7-%EF%B8%8F

Also JupyterLab 4 and Notebook 7 will be sibling releases and their final versions are expected in the coming months.

### Proposed Solution

After `0.1.0` is released (https://github.com/jupyterlite/jupyterlite/issues/383), we can start updating the `@jupyterlab` packages to 4.0 and the `@jupyter-notebook` packages to 7.0.

#### TODO

- [ ] Reuse upstream Playwright config, fix TODO added in https://github.com/jupyterlite/jupyterlite/pull/923
- [ ] Check https://github.com/jupyterlite/jupyterlite/pull/457
- [ ] Check or close https://github.com/jupyterlite/jupyterlite/pull/898

### Additional context

This is likely to land in a `0.2.0` (or later) release of JupyterLite.

**Comment by bollwyvl** [comment]
Starting a `next` branch already might be interesting... though I don't know who would have a ton of time to work on it at the moment with everything else going on.

**Comment by jtpio** [comment]
Right, maybe that's why keeping `main` on the latest versions would be easier w.r.t maintenance.

Nothing urgent yet, just so we have this on the radar.

**Comment by jtpio** [comment]
Also all the RTC changes moving more logic to the backend (with ypy, jupyter_ydoc and so on) might require quite a lot changes here as well...

Unless most of it can be done in https://github.com/jupyterlite/jupyterlab-webrtc-docprovider directly.

So starting to update to the lab 4 and notebook 7 packages at some point soon will hopefully help catch issues that can be reported and fixed upstream before the final releases.

**Comment by bollwyvl** [comment]
Looks like we'll get a preview of the pain involved in a much shorter timeframe with https://github.com/jupyterlab/jupyterlab/issues/13221

**Comment by jtpio** [comment]
Thinking we could then get JupyterLite 0.1.0 final released based on JupyterLab 3.5 and RetroLab.

And skip 3.6 to go with lab 4 / nb 7 directly on `main` for the `0.2.0` pre-releases.

**Comment by bollwyvl** [comment]
Well, due to (rightful) semver pins, many extensions relying on volunteer maintainers will take _months_ to be released with l4/n7, while 3.6 will only break _some_ extensions... presumably this was the motivation in the first place of introducing a fairly large change on a point release, which seems in some ways _bigger_ than the 3.1 breaking change.

So from a site owner perspective of ` jupyterlite/jupyterlab-webrtc-docprovider` (which notably are countable on a few hands), being able to use the thousands of nerd-hours of work represented by all the 3.6-compatible extensions and _not_ get critical data loss when using RTC sounds **pretty good** if we can figure it out.

**Comment by bollwyvl** [comment]
... which is of course _not_ to say we someone shouldn't push forward with a jl4-compatible jupyterlab, as that will help folks be able to release their extensions if they are using lite in their docs/test procedure.
